name: MainWorkFlow
on:
  push:
    branches: [ master ]
  # draftを作成する場合は、オートラベルがあった方が便利なので下記のコメントアウトを外す
  pull_request:
    branches: [ master ]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  updateReleaseDraft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ (github.event.head_commit.committer.email == 'noreply@github.com' && 'プルリク') || 'プルリクじゃないよ' }}

        # push時はreleaseのdraftを作成。PR作成時はラベルの自動付与を行う
        # PR経由のpushの場合のみ、releaseを作成して公開する
      - uses: release-drafter/release-drafter@v5
        # if: github.event.head_commit.committer.email == 'noreply@github.com'
        with:
          # デフォルトのバージョン
          version: 'v1.0.0'
          # releaseの公開設定
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
